---
#target section
- hosts: devenv[0]
  user: np
  become: yes
  connection: ssh
  gather_facts: yes
  
  tasks:
    - name : install docker
      action: yum pkg=docker state=present
    - name: start docker
      action: service name=docker state=started
    - name: install
      command: pip3 install docker-py
    - name: pull tomcat
      docker_image:
         name: tomcat:9.0.73
         tag: 9.0.73
         source: pull
      register: z
    - name: creating volume
      file:
        path: /mnt/data
        state: directory
    - name: copy gameoflife
      action: copy src=/mnt/project/gameoflife-web/target/gameoflife.war dest=/mnt/data
    - name: run tomcat
      docker_container:
        name: np
        image: tomcat:9.0.73
        state: started
        detach: true
        exposed_ports:
          - 8080
        ports:
          - 8081:8080
        volumes:
          - /mnt/data:/var/lib/tomcat/webapps
