---
#target section
- hosts: devenv[0]
  user: np
  become: yes
  connection: ssh
  gather_facts: yes
  
  tasks:
    - name : install docker
      action: yum pkg=docker state=present
    - name: start docker
      action: service name=docker state=started
    - name: pull tomcat
      docker_image:
        name: tomcat
        source: pull
        tag : 9
    - name: run tomcat
      docker_container:
        name: np
        image: tomcat
        state: started
        detach: true
        exposed_ports:
          - 8080
        ports:
          - "8081:8080"
